apiVersion: v1
kind: ReplicationController
metadata:
  name: nodeapp
spec:
  replicas: 7
  selector:
    app: nodeapp
  template:
    metadata:
      name: nodeapp
      labels:
        app: nodeapp
    spec:
      containers:
        - name: nodeapp
          image: kammana/nodeapp:v1
          ports:
            - containerPort: 8080
